FROM node:16

WORKDIR /opt/next

ARG NEXT_PUBLIC_ASSETSERVER_URL
ARG NEXT_PUBLIC_HACKERMAN_FLAGS
ARG NEXT_PUBLIC_ELECTION_URL
ARG NEXT_PUBLIC_GUEST_ONLY
ENV NEXT_PUBLIC_ASSETSERVER_URL $NEXT_PUBLIC_ASSETSERVER_URL
ENV NEXT_PUBLIC_HACKERMAN_FLAGS $NEXT_PUBLIC_HACKERMAN_FLAGS
ENV NEXT_PUBLIC_ELECTION_URL $NEXT_PUBLIC_ELECTION_URL
ENV NEXT_PUBLIC_GUEST_ONLY $NEXT_PUBLIC_GUEST_ONLY

COPY rogue-thi-app/package.json rogue-thi-app/package-lock.json ./
RUN npm install
COPY rogue-thi-app/ .

COPY asset-server/download_assets.sh .
RUN ./download_assets.sh

RUN npm run build

USER node
EXPOSE 3000
CMD ["npm", "start"]