FROM python:3
WORKDIR /opt/
## Update Repos and install needed libraries
RUN apt-get update && apt-get install -y libgl1 ghostscript

## Copy paths
COPY python/spo-parser spo-parser/.
COPY python/room-distances room-distances/.
COPY python/course-downloader course-downloader/.
COPY python/thi-translator thi-translator/.
COPY python/install.sh .
COPY python/run.sh .

## Make Bash scripts executable
RUN chmod +x install.sh
RUN chmod +x run.sh

## Run Pip Installation (Only needed Once)
RUN ./install.sh

## Set an entrypoint to run the container once a day
ENTRYPOINT ["bash", "run.sh"] 
